The first attribute of the yaml after the colon got an enter, so the parser did not find the value of the yaml attribute.
Was: title: Github & Praqma - our NextGen Software Development Seminar
Became: title: (new line)

Error: could not read file /Users/timea/Repos/praqma.com/_posts/2016-06-30-Github & Praqma Seminar.md: (<unknown>): could not find expected ':' while scanning a simple key at line 3 column 1
Github & Praqma - our NextGen Software Development Seminar