End of the Liquid for loop tag missing
Was:
<nav class="about-menu">
  {% for a in site.about-pages %}
    <div class="menu-item{% if a.url == page.url %} active{% endif %}">
      <a href="{{ a.url }}">
        <img src="{{ a.avatar }}" alt="{{ a.title }}">
        <h3>
          {{ a.title }}
        </h3>
        <p>
          {{ a.caption }}
        </p>
      </a>
    </div>
  {% endfor %}
</nav>

Became:
<nav class="about-menu">
  {% for a in site.about-pages %}
    <div class="menu-item{% if a.url == page.url %} active{% endif %}">
      <a href="{{ a.url }}">
        <img src="{{ a.avatar }}" alt="{{ a.title }}">
        <h3>
          {{ a.title }}
        </h3>
        <p>
          {{ a.caption }}
        </p>
      </a>
    </div>

</nav>

Error:
Liquid Exception: Liquid syntax error (line 4): 'for' tag was never closed in _includes/about-menu.html, included in _layouts/about-page.html
...error:
             Error: Liquid syntax error (line 4): 'for' tag was never closed
             Error: Run jekyll build --trace for more information.