Missing | (pipe)
Was:
  -
    name: Atlassian
    logo: /images/partners/atlassian.png
    link: http://atlassian.com/
    description:
      **Atlassian** is an enterprise software company that develops a suite of products supporting the entire product development process.

      As an official Atlassian Expert Partner Praqma offers full-service assistance tailored to our clients' specific needs on the entire Atlassian tool suite.
      We provide consultancy, plugin development, training, support and migration to Git and Stash from Subversion, ClearCase, etc.

Became:
  -
    name: Atlassian
    logo: /images/partners/atlassian.png
    link: http://atlassian.com/
    description:
      **Atlassian** is an enterprise software company that develops a suite of products supporting the entire product development process.

      As an official Atlassian Expert Partner Praqma offers full-service assistance tailored to our clients' specific needs on the entire Atlassian tool suite.
      We provide consultancy, plugin development, training, support and migration to Git and Stash from Subversion, ClearCase, etc.

Error: could not read file /Users/timea/Repos/praqma.com/_about-pages/partners.md: (<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 14 column 7