Missing colon from the list declaration in the front matter
Was:
customers:
  -
    name: Agnitio
    logo: 	/images/customers/agnitio.png
    link: http://agnitio.com/
Became:
customers
  -
    name: Agnitio
    logo: /images/customers/agnitio.png
    link: http://agnitio.com/

Error: could not read file /Users/timea/Repos/praqma.com/_about-pages/customers.md: (<unknown>): could not find expected ':' while scanning a simple key at line 11 column 1